---
- import_tasks: 01ssh.yml
- import_tasks: 02debian.yml
- import_tasks: 03ntp.yml
- when: ansible_service_mgr == "systemd"
  import_tasks: 04systemd.yml
- import_tasks: 05tools.yml
- import_tasks: 06net.yml
