---
# Build-related directories
global_artifacts_dir: "{{ inventory_dir }}/artifacts"
global_cache_dir: "{{ inventory_dir }}/.cache"

# Directory for static assets
global_files_dir: "{{ inventory_dir }}/files"

# Default credentials
## Root password; by default, undefined
root_password: "{{ vault_root_password }}"
## SSH keys for root, default to NOC's

ssh_users_root: "{{ user_groups.noc }}"

acmetool_account_email: noc@realraum.at
