---
openwrt_arch: ar71xx
openwrt_target: generic
openwrt_profile: ubnt-unifiac-lite
openwrt_output_image_suffixes:
  - "generic-{{ openwrt_profile }}-squashfs-sysupgrade.bin"

openwrt_mixin:
  /etc/dropbear/authorized_keys:
    content: |-
      {% for key in noc_ssh_keys %}
      {{ key }}
      {% endfor %}

openwrt_uci:
  system:
    - name: system
      options:
        hostname: '{{ inventory_hostname }}'
        timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
        ttylogin: '0'
        log_size: '64'
        urandom_seed: '0'

    - name: timeserver 'ntp'
      options:
        enabled: '1'
        enable_server: '0'
        server:
          - '0.lede.pool.ntp.org'
          - '1.lede.pool.ntp.org'
          - '2.lede.pool.ntp.org'
          - '3.lede.pool.ntp.org'

  network:
    - name: globals 'globals'
      options:
        ula_prefix: fdc9:e01f:83db::/48

    - name: interface 'loopback'
      options:
        ifname: lo
        proto: static
        ipaddr: 127.0.0.1
        netmask: 255.0.0.0

    - name: interface 'mgmt'
      options:
        type: bridge
        ifname: "eth0.{{ net.mgmt.vlan }}"
        accept_ra: 0
        proto: static
        ipaddr: "{{ net.mgmt.prefix | ipaddr(net.mgmt.offsets.accesspoints + groups.accesspoints.index(inventory_hostname)) | ipaddr('address') }}"
        netmask: "{{ net.mgmt.prefix | ipaddr('netmask') }}"
        gateway: "{{ net.mgmt.gw }}"
        dns: "{{ net.mgmt.dns | join(' ') }}"
        dns_search: realraum.at

    - name: interface 'iot'
      options:
        type: bridge
        ifname: "eth0.{{ net.iot.vlan }}"
        accept_ra: 0
        proto: none

    - name: interface 'lan'
      options:
        type: bridge
        ifname: "eth0.{{ net.lan.vlan }}"
        accept_ra: 0
        proto: none
