---
- name: install classic network config
  import_tasks: classic.yml
  when: ansible_distribution == "Debian" or (ansible_distribution == "Ubuntu" and (ansible_distribution_major_version | int) < 18)

- name: install basic netplan config
  import_tasks: netplan.yml
  when:  ansible_distribution == "Ubuntu" and (ansible_distribution_major_version | int) >= 18

- name: remove resolvconf package
  apt:
    name: resolvconf
    state: absent
    purge: yes

- name: generate resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
