---
sudo: no
language: python
addons:
  apt:
    packages:
      - graphviz
      - ikiwiki
      - imagemagick
      - libimage-magick-perl
      - libtext-markdown-discount-perl
      - libtext-typography-perl

install:
  - pip install ansible
  - pip install ansible-lint
  - ansible --version
  - ansible-lint --version

script:
  - pushd ./ansible
  - ansible-lint _lint_roles.yml
  - popd
  - make -C doc

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: doc/dest
  fqdn: noc.realraum.at
  github-token: $GITHUB_TOKEN  # Set as a secure variable
  keep-history: true
  on:
    branch: master
