---
sshd_allowusers_host:
  - spaceapi

r3status_spaceapi_path: /dev/shm/spaceapi
r3status_ics_path: /dev/shm/ics
r3status_spaceapi_update_user_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJG4w4B95bogd2HOCZNY+OMx+fdo6iPI2tLUPu3RJOUp realraum@iotscripts.mgmt.realraum.at

r3status_www_content:
  url: 'https://github.com/realraum/infokiosk/archive/c2571da52f5c68d11d8d2e2d00a4580aea7b83e7.tar.gz'
  sha256: '406844afd3ebc483ddbfc06a398182566579b9be0b935f83bcacfd2479cc54f5'


acmetool_directory_server: "{{ acmetool_directory_server_le_live }}"

ssmtp_root: postmaster
ssmtp_mailhub: 89.106.215.28 #aka vex1
ssmtp_hostname: vex2.realraum.at
smtp_from_line_override: YES
# ssmtp_auth_user:
# smtp_auth_pass:
# ssmtp_use_starttls:
