---
sshd_allowusers_host:
  - spaceapi

r3status_spaceapi_path: /dev/shm/spaceapi
r3status_ics_path: /dev/shm/ics
r3status_spaceapi_update_user_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJG4w4B95bogd2HOCZNY+OMx+fdo6iPI2tLUPu3RJOUp realraum@iotscripts.mgmt.realraum.at

r3status_www_content:
  url: 'https://github.com/realraum/infokiosk/archive/94e29c6a342a455bdef5a4088aa51dcd38e4e101.tar.gz'
  sha256: 'f8b97765fa331aad0b26e0357644af83fb0c1794702fecfdae6918e3c05cee5c'


acmetool_directory_server: "{{ acmetool_directory_server_le_live }}"

ssmtp_root: postmaster
ssmtp_mailhub: 89.106.215.28 #aka vex1
ssmtp_hostname: vex2.realraum.at
smtp_from_line_override: YES
# ssmtp_auth_user:
# smtp_auth_pass:
# ssmtp_use_starttls:
