---
ssh_users_root:
  - equinox
  - nicoo
  - gebi

#sshd_allowusers_host:
#  - ...

# SSH configuration
## There are no individual user accounts
localconfig_ssh_config_user: root

# VM installation
vm_host: alfred

install:
  host: "{{ vm_host }}"
  mem: 2048
  numcpu: 2
  disks:
    primary: /dev/vda
    virtio:
      vda:
        vg: "{{ vm_host }}"
        lv: "{{ inventory_hostname }}"
        size: 10g
  interfaces:
  - bridge: "{{ hostvars[vm_host].vm_host.network.interface }}"
    name: mgmt0
  autostart: True

network:
  nameservers: "{{ hostvars[vm_host].vm_host.network.nameservers }}"
  domain: realraum.at
  systemd_link:
    interfaces: "{{ install.interfaces }}"
  primary:
    interface: mgmt0
    ip: "{{ (hostvars[vm_host].vm_host.network.ip+'/'+hostvars[vm_host].vm_host.network.mask) | ipaddr(hostvars[vm_host].vm_host.network.indices[inventory_hostname]) | ipaddr('address') }}"
    mask: "{{ hostvars[vm_host].vm_host.network.mask }}"
    gateway: "{{ hostvars[vm_host].vm_host.network.gateway | default(hostvars[vm_host].vm_host.network.ip) }}"
