---
dependencies:
  - role: preseed
    # TODO: Find a way to eliminate the duplicate defaults.
    ssh_keys: "{{ hostvars[hostname].ssh_keys | default(noc_ssh_keys) }}"
    install_interface: enp1s1
