---
vm_host:
  installer:
    net_if: br-mgmt
    preseed_path: /srv/preseed
    path: /srv/installer
    distros:
    - distro: debian
      codename: stretch
      arch:
      - amd64
      - i386
    - distro: ubuntu
      codename: xenial
      arch:
      - amd64
      - i386
  network:
    interface: br-mgmt
    ip: 192.168.33.65
    mask: 255.255.255.0
    gateway: 192.168.33.1
    nameservers:
    - 192.168.33.1
    - 10.12.0.10
    indices:
      testvm: 200
