name: realraum-k8s
description: |
  A Kubernetes/Talos cluster in realraum, declaratively managed.
runtime:
  name: python
  options: {}
config:
  bootstrapNode:
    type: integer
    description: Index of the node to use in bootstrapping
    value: 0 # HACK due to pulumi#21797
