---
- block:
    - name: Create temporary workdir
      tempfile:
        state: directory
      register: tmpdir

    - import_role:
        name: preseed
      vars:
        preseed_tmpdir: "{{ tmpdir.path }}"

    - name: Copy the preseed initramfs to the artifacts directory
      copy:
        src: "{{ tmpdir.path }}/initrd.preseed.gz"
        dest: "{{ artifacts_dir }}/"


  always:
    - name: Cleanup temporary workdir
      file:
        path: "{{ tmpdir.path }}"
        state: absent
