---
localconfig_ssh_config_user: root

vm_install_host: alfred

vm_install:
  host: "{{ vm_install_host }}"
  mem: 1024
  numcpu: 2
  disks:
    primary: vda
    virtio:
      vda:
        vg: alfred
        lv: "{{ inventory_hostname }}"
        size: 10g
  interfaces:
  - bridge: "{{ hostvars[vm_install_host].vm_host.network.interface }}"
    name: mgmt0
  - bridge: "br-svc"
    name: svc0
  autostart: True

vm_network:
  nameservers: "{{ hostvars[vm_install_host].vm_host.network.nameservers }}"
  domain: realraum.at
  systemd_link:
    interfaces: "{{ vm_install.interfaces }}"
  primary:
    interface: mgmt0
    ip: "{{ (hostvars[vm_install_host].vm_host.network.ip+'/'+hostvars[vm_install_host].vm_host.network.mask) | ipaddr(hostvars[vm_install_host].vm_host.network.indices[inventory_hostname]) | ipaddr('address') }}"
    mask: "{{ hostvars[vm_install_host].vm_host.network.mask }}"
    gateway: "{{ hostvars[vm_install_host].vm_host.network.gateway | default(hostvars[vm_install_host].vm_host.network.ip) }}"
