---
vm_install_host: alfred.mgmt

vm_install:
  host: "{{ vm_install_host }}"
  mem: 1024
  numcpu: 2
  disks:
    primary: vda
    virtio:
      vda:
        vg: storage
        lv: "{{ inventory_hostname }}"
        size: 10g
  interfaces:
  - idx: 1
    bridge: "{{ hostvars[vm_install_host].vm_host.network.interface }}"
    name: primary0
  autostart: True

vm_network:
  systemd_link:
    interfaces: "{{ vm_install.interfaces }}"
  primary:
    interface: primary0
    ip: "{{ (hostvars[vm_install_host].vm_host.network.ip+'/'+hostvars[vm_install_host].vm_host.network.mask) | ipaddr(hostvars[vm_install_host].vm_host.network.indices[inventory_hostname]) | ipaddr('address') }}"
    mask: "{{ hostvars[vm_install_host].vm_host.network.mask }}"
    gateway: "{{ hostvars[vm_install_host].vm_host.network.gateway | default(hostvars[vm_install_host].vm_host.network.ip) }}"
    nameservers: "{{ hostvars[vm_install_host].vm_host.network.nameservers }}"
    domain: realraum.at
