---
- block:
    - name: remove legacy systemd.link units
      with_items:
        - 50-virtio-kernel-names.link
        - 99-default.link
      file:
        name: "/etc/systemd/network/{{ item }}"
        state: absent

    - name: install systemd network link units
      template:
        src: systemd.link.j2
        dest: "/etc/systemd/network/{{ '%02d' | format(item.idx + 10) }}-{{ item.name }}.link"
      with_items: "{{ vm_network.systemd_link.interfaces }}"
      notify: rebuild initramfs

  when: vm_network.systemd_link is defined

- name: install basic interface config
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    mode: 0644
