---
- name: install dependencies
  apt:
    name:
      - qemu-kvm
      - # configuration package, pulls in libvirt-clients and libvirt-daemon
        libvirt-daemon-system
      - python-libvirt
      - haveged
    state: present

- name: configure haveged
  lineinfile:
    regexp: "^#?DAEMON_ARGS"
    line: 'DAEMON_ARGS="-w 3072"'
    path: /etc/default/haveged
  notify: restart haveged

- name: make sure installer directories exists
  with_items:
    - "{{ debian_installer_path }}"
    - "{{ preseed_path }}"
  file:
    name: "{{ item }}"
    state: directory
