---
- name: enable serial console in grub and for kernel
  with_dict:
    GRUB_TIMEOUT: 2
    GRUB_CMDLINE_LINUX: '"console=ttyS0,115200n8"'
    GRUB_TERMINAL: serial
    GRUB_SERIAL_COMMAND: >-
      "serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1"
  lineinfile:
    dest: /etc/default/grub
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  notify: update grub
  loop_control:
    label: "{{ item.key }}"
