---
network:
  nameservers: "{{ net.mgmt.dns }}"
  domain: realraum.at
  primary:
    interface: enp1s0
    ip: "{{ net.mgmt.prefix | ipaddr(250) | ipaddr('address') }}"
    mask: "{{ net.mgmt.prefix | ipaddr('netmask') }}"
    gateway: "{{ net.mgmt.gw }}"

install:
  disks:
    primary: sda
