apiVersion: v1alpha1
kind: LinkAliasConfig
name: trunk
selector:
  match: |
    "0000:01:00.0" == link.bus_path
---
apiVersion: v1alpha1
kind: LinkConfig
name: trunk
up: true
addresses: [] # No untagged traffic on this interface
---
apiVersion: v1alpha1
kind: VLANConfig
name: mgmt
vlanID: 32
vlanMode: 802.1q
parent: trunk
up: True
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: mgmt
clientIdentifier: mac
