- name: Install rngd
  apt:
    name: rng-tools
    state: present

- name: Configure rngd [1/2]
  lineinfile:
    path: /etc/default/rng-tools
    line: '{{ item.key }}={{ item.value }}'
    regexp: '^#?{{ item.key }}='
  with_dict: '{{ rngd_config }}'
  loop_control:
    label: "{{ item.key }}"
  notify: restart rngd

- name: Configure rngd [2/2]
  lineinfile:
    path: /etc/default/rng-tools
    regexp: '^{{ item.key }}=(?!{{ item.value }})'
    state: absent
  with_dict: '{{ rngd_config }}'
  loop_control:
    label: "{{ item.key }}"
  notify: restart rngd

- name: Provide a root shell on the VM console [1/2]
  file:
    path: /etc/systemd/system/serial-getty@ttyS0.service.d/
    state: directory

- name: Provide a root shell on the VM console [2/2]
  copy:
    dest: /etc/systemd/system/serial-getty@ttyS0.service.d/autologon.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --keep-baud 115200,38400,9600 --noclear --autologin root --login-pause --host {{ vm_install_host }} %I $TERM
