- name: Install and configure rngd (on kernel < 3.17)
  when: ansible_kernel is version('3.17', '<')
  import_tasks: rngd.yml

- name: Uninstall rngd (on kernel >= 3.17)
  when: ansible_kernel is version('3.17', '>=')
  apt:
    name: rng-tools
    state: absent
    purge: yes


- name: Provide a root shell on the VM console [1/2]
  file:
    path: /etc/systemd/system/serial-getty@ttyS0.service.d/
    state: directory

- name: Provide a root shell on the VM console [2/2]
  copy:
    dest: /etc/systemd/system/serial-getty@ttyS0.service.d/autologon.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --keep-baud 115200,38400,9600 --noclear --autologin root --login-pause --host {{ vm_host }} %I $TERM
